### ISSUE TITLE
__decode_JWT Signature verfication failed.

### ISSUE THREAD

**Issue by Jeremy-Code-F** [425show/fastapi_microsoft_identity#7]
Hi I'm trying to utilize this library along with https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-react

I'm getting an error in the __decode_JWT function

Signature verification failed.

Inside that function 

token_version = '1.0'
_issuer = 'https://sts.windows.net/my_tenant_id/'
_audience = 'api://my_client_id'

It fails on this line 

```
payload = jwt.decode(
            token, rsa_key, algorithms=["RS256"], audience=_audience, issuer=_issuer
        )
```

token and rsa_key both have values in them. any idea what may be causing this issue? 

fastapi==0.73.0
fastapi-microsoft-identity==0.1.6

Thanks

**Comment by Jeremy-Code-F** [comment]
My issue was in how the front end was requesting a token not in this package.

**Comment by exhuma** [comment]
Do you have any more detail on this? I am running in the same issue and can't tell what's wrong.

I am using msal on the frontend and I receive a token. I can even use that token to access the graph-api from the front-end. But on my own back-end, the verification with this library fails with the same error.
